version: '2.2'
services:
  ctf:
      image: bamboofox/pwn:base
      network_mode: "bridge"
      volumes:
          - ./share:/home/ctf/:ro
          - ./xinetd:/etc/xinetd.d/xinetd:ro
      ports:
          - "10000:5566"
      expose:
          - "5566"
      cpus: 0.02
      mem_limit: 30M
      restart: always